language: node_js
node_js:
  - "8"
before_install:
  - npm install -g npm@latest greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
install: npm ci
jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
#cache:
#  directories:
#    - node_modules
