language: node_js
node_js:
  - "8"
before_install:
  - if [[ "$TRAVIS_BRANCH" =~ ^greenkeeper\/ ]]; then npm install -g greenkeeper-lockfile@1; fi
before_script: if [[ "$TRAVIS_BRANCH" =~ ^greenkeeper\/ ]]; then greenkeeper-lockfile-update; fi
after_script: if [[ "$TRAVIS_BRANCH" =~ ^greenkeeper\/ ]]; then greenkeeper-lockfile-upload; fi
install: if [[ "$TRAVIS_BRANCH" =~ ^greenkeeper\/ ]]; then npm install; fi
jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  directories:
    - node_modules
